name: Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/northcutted/resume-ci:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: "Create a folder called output"
        run: |
          mkdir output
          cp index.html output/index.html
          cp script.js output/script.js
          cp style.css output/style.css
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: output
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
